trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

jobs:
  - job: "Windows_PS51_Build_Continuous_Integration_02"
    pool: "DAS - Continuous Deployment"
    workspace:
      clean: all
    steps:
      - task: PowerShell@2
        inputs:
          filePath: 'Tests/Invoke-Tests.ps1'
      - task: PublishTestResults@2
        displayName: 'Publish Test Results **/TEST-*.xml'
        inputs:
          testResultsFormat: NUnit
          testResultsFiles: '**/TEST-*.xml'
        condition: succeededOrFailed()

  - job: "Linux_PSCore_Build_DAS_Continuous_Integration"
    pool: "DAS - Continuous Integration"
    workspace:
      clean: all
    steps:
      - task: PowerShell@2
        inputs:
          filePath: 'Tests/Invoke-Tests.ps1'
          pwsh: true
      - task: PublishTestResults@2
        displayName: 'Publish Test Results **/TEST-*.xml'
        inputs:
          testResultsFormat: NUnit
          testResultsFiles: '**/TEST-*.xml'
        condition: succeededOrFailed()
