trigger: none

pool:
  name: DAS - Continuous Deployment Agents

stages:
- stage: DevTest
  jobs:
  - template: pipeline-templates/jobs/addIpFirewallRules.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
- stage: PP
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: pipeline-templates/jobs/addIpFirewallRules.yml
    parameters:
      ServiceConnection: SFA-DIG-PreProd-ARM
