name: Release

on:
  push:
    branches:
      - 'master'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: "5.x"
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.14
        with:
          useConfigFile: true
      - name: Create Release
        id: create_release
        run: |
          gh release create ${{ steps.gitversion.outputs.majorMinorPatch }} \
            --title "${{ steps.gitversion.outputs.majorMinorPatch }}" \
            --generate-notes \
            --target ${{ github.sha }} ${{ github.workspace }}/Infrastructure-Scripts/**/*.ps1 ${{ github.workspace }}/Infrastructure-Scripts/*.ps1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
